#! /bin/sh


#polybar &
# Launch polybar on internal monitor (eDP)
if xrandr | grep "$INTERNAL_MONITOR" | grep "connected"; then
    MONITOR=$INTERNAL_MONITOR polybar --reload example &
fi
pgrep -x sxhkd > /dev/null || sxhkd &



~/.config/bspwm/monitor-setup.sh &




#bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap           4

#added while making changes in polybar autohide
bspc config bottom_padding 0


bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#~/.config/polybar/polybar_autohide.sh &

bspc config normal_border_color "#484848"
bspc config focused_border_color "#1F8999"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

xsetroot -cursor_name left_ptr &
feh --bg-fill ~/Pictures/wallpapers/durga_maa.jpg
#$HOME/.config/polybar/launch.sh &
